name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14

      - name: Install Packages
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn test --watchAll false
          yarn test:demo --watchAll false

      - name: Build
        run: |
          yarn build
